<a href="https://colab.research.google.com/github/RoshanSekar1106/AI-INTERNSHIP/blob/main/apriori_for_Market_Basket_Optimisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/sample_data/Market_Basket_Optimisation.csv')

In [ ]:
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe()

       olive oil
count        0.0
mean         NaN
std          NaN
min          NaN
25%          NaN
50%          NaN
75%          NaN
max          NaN

In [ ]:
df.isna().sum()

shrimp                  0
almonds              1754
avocado              3112
vegetables mix       4156
green grapes         4972
whole weat flour     5637
yams                 6132
cottage cheese       6520
energy drink         6847
tomato juice         7106
low fat yogurt       7245
green tea            7347
honey                7414
salad                7454
mineral water        7476
salmon               7493
antioxydant juice    7497
frozen smoothie      7497
spinach              7498
olive oil            7500
dtype: int64

In [ ]:
transactions=[]
for i in range(0,len(df)):
    for j in range(0,len(df.columns)):
      transactions.append(str(df.values[i,j]))

In [ ]:
from apyori import apriori

rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

result = list(rules)

In [ ]:
result

[RelationRecord(items=frozenset({'b', ' '}), support=0.023066666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'b'}), confidence=0.2514169452114518, lift=7.456018541264881), OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({' '}), confidence=0.6840648477659154, lift=7.456018541264881)]),
 RelationRecord(items=frozenset({'c', ' '}), support=0.030446666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'c'}), confidence=0.3318558349077169, lift=4.809504853735027), OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({' '}), confidence=0.441256038647343, lift=4.809504853735027)]),
 RelationRecord(items=frozenset({'d', ' '}), support=0.018046666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({' '}), confidence=0.8193099273607748, lift=8.930132909759934)]),
 RelationRecord(items=frozenset({'e', ' '}), support=0.08037333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'e'}), confidence=0.8760354599622148, lift=5.6314956284534246), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({' '}), confidence=0.5166709522585069, lift=5.6314956284534246)]),
 RelationRecord(items=frozenset({'f', ' '}), support=0.032613333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'f'}), confidence=0.35547158843191395, lift=10.436629137754373), OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({' '}), confidence=0.9575259346251713, lift=10.436629137754373)]),
 RelationRecord(items=frozenset({'g', ' '}), support=0.03956666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'g'}), confidence=0.43125999128033715, lift=6.526990080925293), OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({' '}), confidence=0.5988295832912925, lift=6.526990080925293)]),
 RelationRecord(items=frozenset({'h', ' '}), support=0.03626, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'h'}), confidence=0.39521871820956256, lift=5.760086254511697), OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({' '}), confidence=0.5284687135639332, lift=5.760086254511697)]),
 RelationRecord(items=frozenset({'i', ' '}), support=0.04561333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'i'}), confidence=0.49716610957709634, lift=6.057091978278464), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({' '}), confidence=0.5557179987004548, lift=6.057091978278463)]),
 RelationRecord(items=frozenset({'l', ' '}), support=0.03888, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'l'}), confidence=0.4237756140095916, lift=6.2216249487558715), OrderedStatistic(items_base=frozenset({'l'}), items_add=frozenset({' '}), confidence=0.5708133502985221, lift=6.221624948755872)]),
 RelationRecord(items=frozenset({'m', ' '}), support=0.024346666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'m'}), confidence=0.26536840575497744, lift=5.196509251076582), OrderedStatistic(items_base=frozenset({'m'}), items_add=frozenset({' '}), confidence=0.4767624020887728, lift=5.196509251076582)]),
 RelationRecord(items=frozenset({'o', ' '}), support=0.04224666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'o'}), confidence=0.460470861793344, lift=5.8628833943639425), OrderedStatistic(items_base=frozenset({'o'}), items_add=frozenset({' '}), confidence=0.5379000084882438, lift=5.862883394363942)]),
 RelationRecord(items=frozenset({'r', ' '}), support=0.07265333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'r'}), confidence=0.7918907135590757, lift=8.413032582609347), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({' '}), confidence=0.7718676960124655, lift=8.413032582609347)]),
 RelationRecord(items=frozenset({'s', ' '}), support=0.03643333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'s'}), confidence=0.3971079784914983, lift=4.049367557697128), OrderedStatistic(items_base=frozenset({'s'}), items_add=frozenset({' '}), confidence=0.37151597552685245, lift=4.049367557697127)]),
 RelationRecord(items=frozenset({'t', ' '}), support=0.05608666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'t'}), confidence=0.611321028920215, lift=6.920093150557109), OrderedStatistic(items_base=frozenset({'t'}), items_add=frozenset({' '}), confidence=0.6348954795864463, lift=6.9200931505571095)]),
 RelationRecord(items=frozenset({'u', ' '}), support=0.016906666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({' '}), confidence=0.52603194358017, lift=5.733526488666291)]),
 RelationRecord(items=frozenset({'v', ' '}), support=0.009333333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'v'}), items_add=frozenset({' '}), confidence=0.8489993935718617, lift=9.253735578824244)]),
 RelationRecord(items=frozenset({'w', ' '}), support=0.024506666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({' '}), items_add=frozenset({'w'}), confidence=0.26711233832291814, lift=9.633770317008349), OrderedStatistic(items_base=frozenset({'w'}), items_add=frozenset({' '}), confidence=0.8838663140177927, lift=9.633770317008349)]),
 RelationRecord(items=frozenset({'y', ' '}), support=0.01118, ordered_statistics=[OrderedStatistic(items_base=frozenset({'y'}), items_add=frozenset({' '}), confidence=0.6297408937288773, lift=6.863910337111728)]),
 RelationRecord(items=frozenset({'z', ' '}), support=0.007926666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'z'}), items_add=frozenset({' '}), confidence=0.8859910581222057, lift=9.65692913227226)]),
 RelationRecord(items=frozenset({'b', 'd'}), support=0.008826666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'d'}), confidence=0.26176354290233295, lift=11.883938085759668), OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'b'}), confidence=0.400726392251816, lift=11.883938085759668)]),
 RelationRecord(items=frozenset({'b', 'e'}), support=0.03179333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'e'}), confidence=0.94286279161724, lift=6.061087629321419), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'b'}), confidence=0.20437987486071826, lift=6.0610876293214195)]),
 RelationRecord(items=frozenset({'b', 'f'}), support=0.013086666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'f'}), confidence=0.38809806247528666, lift=11.394540883009004), OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'b'}), confidence=0.3842239185750636, lift=11.394540883009004)]),
 RelationRecord(items=frozenset({'b', 'g'}), support=0.01886, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'g'}), confidence=0.559311981020166, lift=8.465018378874474), OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'b'}), confidence=0.28544041973564727, lift=8.465018378874474)]),
 RelationRecord(items=frozenset({'b', 'l'}), support=0.0096, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'l'}), confidence=0.2846975088967971, lift=4.179761802341154)]),
 RelationRecord(items=frozenset({'b', 'o'}), support=0.01468, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'o'}), confidence=0.43534994068801897, lift=5.543034640794741)]),
 RelationRecord(items=frozenset({'b', 'r'}), support=0.03002, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'r'}), confidence=0.8902728351126928, lift=9.45824245817012), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'b'}), confidence=0.31893193568949646, lift=9.45824245817012)]),
 RelationRecord(items=frozenset({'b', 's'}), support=0.019806666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'s'}), confidence=0.5873863187030447, lift=5.9896633450344465), OrderedStatistic(items_base=frozenset({'s'}), items_add=frozenset({'b'}), confidence=0.20197144799456154, lift=5.9896633450344465)]),
 RelationRecord(items=frozenset({'b', 't'}), support=0.012126666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'t'}), confidence=0.35962831158560693, lift=4.070956662730438)]),
 RelationRecord(items=frozenset({'b', 'u'}), support=0.012853333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'b'}), items_add=frozenset({'u'}), confidence=0.3811783313562673, lift=11.859935636473779), OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({'b'}), confidence=0.39991702966189585, lift=11.85993563647378)]),
 RelationRecord(items=frozenset({'b', 'v'}), support=0.006046666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'v'}), items_add=frozenset({'b'}), confidence=0.5500303214069132, lift=16.31169399190134)]),
 RelationRecord(items=frozenset({'z', 'b'}), support=0.0047666666666666664, ordered_statistics=[OrderedStatistic(items_base=frozenset({'z'}), items_add=frozenset({'b'}), confidence=0.5327868852459016, lift=15.800322812749156)]),
 RelationRecord(items=frozenset({'c', 'd'}), support=0.0067733333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'c'}), confidence=0.3075060532687651, lift=4.456609467663262)]),
 RelationRecord(items=frozenset({'c', 'e'}), support=0.06150666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'e'}), confidence=0.8914009661835748, lift=5.730271060578393), OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'c'}), confidence=0.39538870317990915, lift=5.730271060578393)]),
 RelationRecord(items=frozenset({'c', 'f'}), support=0.010593333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'c'}), confidence=0.3110197690350362, lift=4.507532884565742)]),
 RelationRecord(items=frozenset({'c', 'h'}), support=0.03647333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'h'}), confidence=0.5285990338164251, lift=7.7040278927772805), OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'c'}), confidence=0.5315779246016324, lift=7.704027892777281)]),
 RelationRecord(items=frozenset({'c', 'i'}), support=0.028686666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'i'}), confidence=0.41574879227053135, lift=5.065165597837858), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'c'}), confidence=0.34949642625081223, lift=5.065165597837858)]),
 RelationRecord(items=frozenset({'c', 'k'}), support=0.02158, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'k'}), confidence=0.31275362318840577, lift=9.36949140768142), OrderedStatistic(items_base=frozenset({'k'}), items_add=frozenset({'c'}), confidence=0.6464949071300179, lift=9.369491407681418)]),
 RelationRecord(items=frozenset({'c', 'l'}), support=0.023186666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'l'}), confidence=0.33603864734299516, lift=4.9335222767396765), OrderedStatistic(items_base=frozenset({'l'}), items_add=frozenset({'c'}), confidence=0.34041303709503773, lift=4.9335222767396765)]),
 RelationRecord(items=frozenset({'c', 'o'}), support=0.03387333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'o'}), confidence=0.4909178743961352, lift=6.250545892489626), OrderedStatistic(items_base=frozenset({'o'}), items_add=frozenset({'c'}), confidence=0.4312876665817842, lift=6.250545892489625)]),
 RelationRecord(items=frozenset({'p', 'c'}), support=0.01292, ordered_statistics=[OrderedStatistic(items_base=frozenset({'p'}), items_add=frozenset({'c'}), confidence=0.33236151603498537, lift=4.8168335657244254)]),
 RelationRecord(items=frozenset({'c', 'r'}), support=0.02698, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'r'}), confidence=0.39101449275362316, lift=4.154130881297789), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'c'}), confidence=0.28663503080954744, lift=4.154130881297789)]),
 RelationRecord(items=frozenset({'c', 's'}), support=0.0332, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'s'}), confidence=0.48115942028985503, lift=4.906452280318033), OrderedStatistic(items_base=frozenset({'s'}), items_add=frozenset({'c'}), confidence=0.33854520734194427, lift=4.906452280318033)]),
 RelationRecord(items=frozenset({'t', 'c'}), support=0.023666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'c'}), items_add=frozenset({'t'}), confidence=0.3429951690821256, lift=3.882671146503572), OrderedStatistic(items_base=frozenset({'t'}), items_add=frozenset({'c'}), confidence=0.2679043091087465, lift=3.8826711465035726)]),
 RelationRecord(items=frozenset({'c', 'u'}), support=0.006953333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({'c'}), confidence=0.21634515660651316, lift=3.135437052268306)]),
 RelationRecord(items=frozenset({'d', 'e'}), support=0.015893333333333332, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'e'}), confidence=0.7215496368038741, lift=4.638400853714798)]),
 RelationRecord(items=frozenset({'f', 'd'}), support=0.008073333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'f'}), confidence=0.3665254237288136, lift=10.76116922280721), OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'d'}), confidence=0.2370326874143668, lift=10.76116922280721)]),
 RelationRecord(items=frozenset({'d', 'g'}), support=0.01048, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'g'}), confidence=0.4757869249394673, lift=7.200891811211794)]),
 RelationRecord(items=frozenset({'h', 'd'}), support=0.0079, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'h'}), confidence=0.3586561743341405, lift=5.2272081374000265)]),
 RelationRecord(items=frozenset({'o', 'd'}), support=0.012366666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'o'}), confidence=0.5614406779661016, lift=7.148468015865822)]),
 RelationRecord(items=frozenset({'d', 'r'}), support=0.0153, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'r'}), confidence=0.6946125907990315, lift=7.379551570214231)]),
 RelationRecord(items=frozenset({'d', 's'}), support=0.010353333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'s'}), confidence=0.47003631961259085, lift=4.793028412093041)]),
 RelationRecord(items=frozenset({'t', 'd'}), support=0.006506666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'t'}), confidence=0.29539951573849876, lift=3.3438930919005974)]),
 RelationRecord(items=frozenset({'u', 'd'}), support=0.005353333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'d'}), items_add=frozenset({'u'}), confidence=0.24303874092009684, lift=7.56187743995323)]),
 RelationRecord(items=frozenset({'f', 'e'}), support=0.028513333333333335, ordered_statistics=[OrderedStatistic(items_base=frozenset({'f'}), items_add=frozenset({'e'}), confidence=0.8371501272264632, lift=5.3815256314377935)]),
 RelationRecord(items=frozenset({'g', 'e'}), support=0.05537333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'g'}), confidence=0.35596125824976427, lift=5.387366435018126), OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'e'}), confidence=0.8380587226314196, lift=5.387366435018125)]),
 RelationRecord(items=frozenset({'h', 'e'}), support=0.05872666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'h'}), confidence=0.377517785206137, lift=5.50210530323752), OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'e'}), confidence=0.8559075009716285, lift=5.502105303237519)]),
 RelationRecord(items=frozenset({'i', 'e'}), support=0.06298, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'i'}), confidence=0.4048598611468243, lift=4.932503181613357), OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'e'}), confidence=0.7673001949317738, lift=4.932503181613357)]),
 RelationRecord(items=frozenset({'k', 'e'}), support=0.023793333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'k'}), items_add=frozenset({'e'}), confidence=0.7128020770920711, lift=4.582168147930516)]),
 RelationRecord(items=frozenset({'l', 'e'}), support=0.0477, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'l'}), confidence=0.30663409616868087, lift=4.501821907145163), OrderedStatistic(items_base=frozenset({'l'}), items_add=frozenset({'e'}), confidence=0.7003034158755016, lift=4.501821907145163)]),
 RelationRecord(items=frozenset({'m', 'e'}), support=0.031086666666666665, ordered_statistics=[OrderedStatistic(items_base=frozenset({'m'}), items_add=frozenset({'e'}), confidence=0.6087467362924281, lift=3.9132600687350743)]),
 RelationRecord(items=frozenset({'o', 'e'}), support=0.05723333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'o'}), confidence=0.36791805948401474, lift=4.684467271250506), OrderedStatistic(items_base=frozenset({'o'}), items_add=frozenset({'e'}), confidence=0.7287157287157287, lift=4.684467271250505)]),
 RelationRecord(items=frozenset({'p', 'e'}), support=0.03012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'p'}), items_add=frozenset({'e'}), confidence=0.7748242154004459, lift=4.980870502702789)]),
 RelationRecord(items=frozenset({'r', 'e'}), support=0.084, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'r'}), confidence=0.5399845718693752, lift=5.736786300758289), OrderedStatistic(items_base=frozenset({'r'}), items_add=frozenset({'e'}), confidence=0.8924144769459594, lift=5.736786300758289)]),
 RelationRecord(items=frozenset({'s', 'e'}), support=0.07923333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'s'}), confidence=0.5093425902117082, lift=5.193840144918847), OrderedStatistic(items_base=frozenset({'s'}), items_add=frozenset({'e'}), confidence=0.8079537729435758, lift=5.1938401449188465)]),
 RelationRecord(items=frozenset({'t', 'e'}), support=0.07774666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset({'e'}), items_add=frozenset({'t'}), confidence=0.49978572040798835, lift=5.657524568802223), OrderedStatistic(items_base=frozenset({'t'}), items_add=frozenset({'e'}), confidence=0.8800845219228738, lift=5.657524568802223)]),
 RelationRecord(items=frozenset({'u', 'e'}), support=0.022766666666666668, ordered_statistics=[OrderedStatistic(items_base=frozenset({'u'}), items_add=frozenset({'e'}), confidence=0.7083592615639909, lift=4.553608006968314)]),

In [ ]:
data = []

for item in result:
    support = item.support

    for stat in item.ordered_statistics:
        lhs = ', '.join(list(stat.items_base))
        rhs = ', '.join(list(stat.items_add))
        confidence = stat.confidence
        lift = stat.lift

        data.append([lhs, rhs, support, confidence, lift])

rules_df = pd.DataFrame(data,
    columns=['LHS', 'RHS', 'Support', 'Confidence', 'Lift']
)

print(rules_df.head())

  LHS RHS   Support  Confidence      Lift
0       b  0.023067    0.251417  7.456019
1   b      0.023067    0.684065  7.456019
2       c  0.030447    0.331856  4.809505
3   c      0.030447    0.441256  4.809505
4   d      0.018047    0.819310  8.930133

In [ ]:
rules_df

    LHS RHS   Support  Confidence       Lift
0         b  0.023067    0.251417   7.456019
1     b      0.023067    0.684065   7.456019
2         c  0.030447    0.331856   4.809505
3     c      0.030447    0.441256   4.809505
4     d      0.018047    0.819310   8.930133
..   ..  ..       ...         ...        ...
256   u   y  0.009393    0.292263  16.462430
257   y   u  0.009393    0.529103  16.462430
258   v   z  0.004767    0.433596  48.464544
259   z   v  0.004767    0.532787  48.464544
260   y   w  0.003840    0.216297   7.801061

[261 rows x 5 columns]

In [ ]:
rules_df.sort_values(by='Lift',ascending=False)

    LHS RHS   Support  Confidence       Lift
259   z   v  0.004767    0.532787  48.464544
258   v   z  0.004767    0.433596  48.464544
127   f   z  0.007927    0.232727  26.012656
128   z   f  0.007927    0.885991  26.012656
257   y   u  0.009393    0.529103  16.462430
..   ..  ..       ...         ...        ...
132   i   g  0.017147    0.208902   3.161667
131   g   i  0.017147    0.259510   3.161667
73    u   c  0.006953    0.216345   3.135437
197   l   s  0.020587    0.302241   3.081999
198   s   l  0.020587    0.209925   3.081999

[261 rows x 5 columns]